### ISSUE TITLE
Faulty graph functionality

### ISSUE THREAD

**Issue by rishi2019194** [rishi2019194/calorieApp#15]
For a given login session, the code is not fetching the calories intake & burnt for the person corresponding to that email id

**Comment by ananya173147** [comment]
Rishi fixed it

**Comment by rishi2019194** [comment]
Fixed it. By adding dropbox for date

**Comment by rishi2019194** [comment]
Previous code was randomly fetching data from the DB. Therefore fixed it by fetching the current session's email data. Also added legend to the graph
